# Blue-Green Deployment for Layer5

apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer5-refinement-green
  namespace: project-chimera
  labels:
    app: layer5
    component: refinement
    deployment: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: layer5
      component: refinement
      deployment: green
  template:
    metadata:
      labels:
        app: layer5
        component: refinement
        deployment: green
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: layer5
        image: project-chimera/layer5:${GREEN_TAG}
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8080
          name: health
        env:
        - name: DEPLOYMENT_COLOR
          value: "green"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer5-refinement-blue
  namespace: project-chimera
  labels:
    app: layer5
    component: refinement
    deployment: blue
spec:
  replicas: 0  # Start with 0 replicas for blue
  selector:
    matchLabels:
      app: layer5
      component: refinement
      deployment: blue
  template:
    metadata:
      labels:
        app: layer5
        component: refinement
        deployment: blue
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: layer5
        image: project-chimera/layer5:${BLUE_TAG}
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8080
          name: health
        env:
        - name: DEPLOYMENT_COLOR
          value: "blue"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: layer5-refinement-active
  namespace: project-chimera
spec:
  selector:
    app: layer5
    component: refinement
    deployment: green  # Initially points to green
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  - name: health
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: layer5-refinement-green
  namespace: project-chimera
spec:
  selector:
    app: layer5
    component: refinement
    deployment: green
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: layer5-refinement-blue
  namespace: project-chimera
spec:
  selector:
    app: layer5
    component: refinement
    deployment: blue
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: layer5-refinement-ingress
  namespace: project-chimera
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: layer5.project-chimera.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: layer5-refinement-active
            port:
              number: 8080