apiVersion: apps/v1
kind: Deployment
metadata:
  name: chimera-agent
  labels:
    app: chimera-agent
    component: ai-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chimera-agent
  template:
    metadata:
      labels:
        app: chimera-agent
        component: ai-agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      nodeSelector:
        accelerator: nvidia-tesla-k80  # or appropriate GPU selector
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: agent
        image: project-chimera/agent:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8080
          name: metrics
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: NATS_URL
          value: "nats://nats-service:4222"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: chimera-secrets
              key: postgres-url
        - name: MINIO_ENDPOINT
          value: "minio-service:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: chimera-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chimera-secrets
              key: minio-secret-key
        - name: AGENT_ID
          value: "intent-parser-v1"
        - name: MODEL_PATH
          value: "/models/gemma-3-270m-q4.safetensors"
        - name: ADAPTER_PATH
          value: "/models/adapter.safetensors"
        - name: BATCH_WINDOW_MS
          value: "15"
        - name: MAX_TOKENS
          value: "512"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "2000m"
          limits:
            nvidia.com/gpu: 1
            memory: "12Gi"
            cpu: "4000m"
        volumeMounts:
        - name: models-volume
          mountPath: /models
          readOnly: true
        - name: artifacts-volume
          mountPath: /artifacts
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: artifacts-volume
        persistentVolumeClaim:
          claimName: artifacts-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: chimera-agent-service
  labels:
    app: chimera-agent
spec:
  selector:
    app: chimera-agent
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chimera-agent-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: agents.chimera.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chimera-agent-service
            port:
              number: 80