global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${SMTP_FROM:-alerts@project-chimera.com}'
  smtp_auth_username: '${SMTP_USERNAME:-your-email@gmail.com}'
  smtp_auth_password: '${SMTP_PASSWORD:-your-app-password}'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-alerts'
  routes:
  - match:
      severity: critical
    receiver: 'email-alerts'
    continue: true

receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'devops@project-chimera.com'
    subject: '🚨 Project Chimera Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Runbook: {{ .Annotations.runbook_url }}
      {{ end }}

- name: 'slack-alerts'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts'
    title: 'Project Chimera Alert'
    text: |
      {{ range .Alerts }}
      *{{ .Annotations.summary }}*
      {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']