global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agent_service'
    static_configs:
      - targets: ['agent:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  - job_name: 'trainer_service'
    static_configs:
      - targets: ['trainer:8080']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'discovery_service'
    static_configs:
      - targets: ['discovery:8081']
    scrape_interval: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  - job_name: 'evolution_service'
    static_configs:
      - targets: ['evolution:8082']
    scrape_interval: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']