# External Secrets Operator configuration for Kubernetes
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secrets-store
  namespace: default
spec:
  provider:
    gcp:
      auth:
        workloadIdentity:
          clusterLocation: us-east1
          clusterName: project-chimera
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agent-secrets
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: agent-secret
    creationPolicy: Owner
  data:
  - secretKey: database_password
    remoteRef:
      key: prod/chimera/database
  - secretKey: redis_password
    remoteRef:
      key: prod/chimera/redis
  - secretKey: jwt_secret
    remoteRef:
      key: prod/chimera/jwt
  - secretKey: openai_api_key
    remoteRef:
      key: prod/chimera/openai
  - secretKey: huggingface_token
    remoteRef:
      key: prod/chimera/huggingface
---
# SOPS configuration for local secrets management
apiVersion: v1
kind: ConfigMap
metadata:
  name: sops-config
  namespace: default
data:
  sops.yaml: |
    creation_rules:
      - path_regex: configs/.*\\.yaml$
        encrypted_regex: ^(data|stringData)$
        gcp_kms: projects/project-chimera/locations/global/keyRings/chimera-keyring/cryptoKeys/chimera-key
      - path_regex: .*\\.env$
        encrypted_regex: ^(.*_KEY|.*_TOKEN|.*_PASSWORD|.*_SECRET)$
        gcp_kms: projects/project-chimera/locations/global/keyRings/chimera-keyring/cryptoKeys/chimera-key

    # Age keys for local development
    - path_regex: configs/.*\\.yaml$
      encrypted_regex: ^(data|stringData)$
      age: >-
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxdfghbGljaXR5LXJlZ2lzdGVyL3YxCi0+
        RXaCjB2l7XnZ8Y2hpbWVyYS1rZXktcmluZy9jaGltZXJhLWtleQ==
        -----END AGE ENCRYPTED FILE-----