apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: ${POSTGRES_DB:-chimera}
    user: ${POSTGRES_USER:-chimera}
    secureJsonData:
      password: "${POSTGRES_PASSWORD:-changeme123}"
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500